### ISSUE TITLE
Tool for extracting features/metrics from program dependency graphs of C code 

### ISSUE THREAD

**Issue by ainne26** [Frama-C/Frama-C-snapshot#24]
I am a PG student and doing my research on code clone detection.
For this purpose I made program dependency graphs of C code using a tool named frama-c. Now I have to extract features/metrics from these program dependency graphs for further processing. Is there any tool that can extract features/metrics from program dependency graph.
Please help me in this issue ??

**Comment by maroneze** [comment]
I'm afraid the Github issues page is more directed towards bugs and technical issues in Frama-C, while your questions are more about general usage and research-oriented questions. I believe posting them in the [frama-c-discuss](https://lists.gforge.inria.fr/mailman/listinfo/frama-c-discuss) mailing list would be better, since there are more academic researchers over there who could indicate other solutions, beyond Frama-C itself.

**Comment by maroneze** [comment]
You could also try asking questions tagged `frama-c` in [StackOverflow](https://stackoverflow.com/questions/tagged/frama-c), they are likely to reach a much wider audience.

**Comment by ainne26** [comment]
okay thank You Sir.
