### ISSUE TITLE
Frama-c requires Ocaml < 4.08

### ISSUE THREAD

**Issue by LudwikJaniuk** [Frama-C/Frama-C-snapshot#27]
Followed installation instructions on ubuntu. After installing opam (2.0.5) and depext without problems, `opam depext frama-c` did not want to work and produced the following:
```
# Detecting depexts using vars: arch=x86_64, os=linux, os-distribution=ubuntu, os-family=debian
[ERROR] No solution for frama-c: The following dependencies couldn't be met:
          - frama-c → frama-c-base → ocaml < 4.06
              base of this switch (use `--unlock-base' to force)
          - frama-c → ocaml < 4.08.0
              base of this switch (use `--unlock-base' to force)


Command failed: opam list --readonly --external  --resolve=frama-c returned 20
```
Turns out when installing opam, the version of ocaml installed automatically was `4.08.1`. I was able to get frama-c in the end by downgrading ocaml (`opam install ocaml.4.05.0 --unlock-base`) but maybe it would be nice to make frama-c work with the latest version of ocaml.

**Comment by vprevosto** [comment]
There was an OCaml issue in 4.08.0 preventing the use of the bytecode version (https://github.com/ocaml/ocaml/issues/8816), which prompted this requirement. This has been fixed in 4.08.1, but in the mean time we identified an additional compatibility issue, in Frama-C itself, affecting the save/load mechanism. We'll provide a patch for it in the opam package soon.

**Comment by LudwikJaniuk** [comment]
Looking forwards to it!

**Comment by vprevosto** [comment]
19.1 is [here](https://github.com/Frama-C/Frama-C-snapshot/releases/tag/19.1), opam package should follow soon (PR [here](https://github.com/ocaml/opam-repository/pull/14911))
