### ISSUE TITLE
Different properties between Mac and Ubuntu

### ISSUE THREAD

**Issue by aogrcs** [Frama-C/Frama-C-snapshot#8]
Hi, I followed this tutorial: 
http://blog.frama-c.com/index.php?post/2017/03/17/A-simple-tutorial-part-two
both for Mac and ubuntu and the frama-c version is Chlorine.
First I did the operation frama-c test.c sha512.c monocypher.c -cpp-extra-args="-DED25519_SHA512" -save parsed.sav then frama-c -load parsed.sav -val -save value.sav(for -val-builtins-auto is built so I omitted it), at last I using gui to load it: frame-c-gui -load valued.sav.
But under Mac, the number of properties is 12, and for ubuntu this is about 900? What cause this problem? Thanks!
Sincerely

**Comment by maroneze** [comment]
*Some* differences between a Linux and a Mac are not entirely unexpected when using the Frama-C standard library, because its definitions and constants are Linux-oriented (e.g. `SO_REUSEADDR` may be defined as 2 in Linux and as 4 in Mac, and in this case Frama-C's libc uses 2). However, most code abstracts away such values, so in practice such differences should be transparent to the user.

A huge number of differences between two analyses usually indicates that the analysis stopped too early in one case, for instance if some statement was considered definitively invalid because of some parametrization issue. Without knowing exactly what happened, it's hard to pinpoint the exact cause.

I just tried on a Mac the version of monocypher in [open-source-case-studies](https://github.com/Frama-C/open-source-case-studies/tree/master/monocypher), which is similar to the one used in the blog tutorial, and I got about 540 properties *To be validated*. This is the same amount I get when running under Linux.

Consider adding `-report -report-csv monocypher.csv` to the command line which loads `value.sav`, on both of your machines. This will produce a CSV report that you can then upload here so that we can compare and better understand what's going on.

**Comment by aogrcs** [comment]
Hi, I got both the csv files and compared them, I though they were the same. Here are them.
BTW, under MAC I used gmake. Thanks
Sincerely
Please change the file type from txt to csv for the attachment does not support csv!
[monocypher_mac.txt](https://github.com/Frama-C/Frama-C-snapshot/files/2060621/monocypher_mac.txt)
[monocypher_ubuntu.txt](https://github.com/Frama-C/Frama-C-snapshot/files/2060622/monocypher_ubuntu.txt)

**Comment by maroneze** [comment]
If the files are identical, the differences you are observing in the GUI may be related to different *Property filters*. In [this blog post](http://blog.frama-c.com/index.php?post/2016/03/23/Small-improvements-to-the-Frama-C-GUI), in section *Property filters and filtersets*, there is a short description of them, along with a screenshot. These filters are persistent from session to session, so changing them once will keep them modified even when reopening the GUI.

The recommended view for Eva is:

- Click on *Reset all filters to default*;
- Then click on *Reset 'Status' filters to show only unproven/invalid*;
- Then make sure the *Current function* checkbox (first in the list) is *unchecked*;
- Then click *Refresh* to update the list of filters.

This will display all properties that usually concern Eva users, in the entire program

**Comment by aogrcs** [comment]
I click them several times, but I would try again following your tutorial! Thanks

**Comment by maroneze** [comment]
Could you please confirm if it worked? Otherwise, please consider submitting screenshots or the CSV logs produced by `-report`, so that we can further investigate it.

**Comment by aogrcs** [comment]
Hi
It worked, I thought maybe I forgot to uncheck the Current function checkbox! Thanks!
Sincerely!
Sorry for such late feedback

**Comment by maroneze** [comment]
Thanks for the reply, glad to know it worked. In any case, we're working on improving that part of the GUI, to prevent mistakes and to make it easier to use.
